services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - docker-wordnet
    environment:
      - PORT=3000

  docker-wordnet:
    build: ./docker-wordnet
    ports:
      - "5001:5001"

