services:
  password-generator:
    container_name: pwgen
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:3000"
    volumes:
      # Persist the cache directory across container restarts
      - ./cache:/app/cache
    environment:
      NODE_ENV: production

